name: adorable
services:
  client:
    build: 
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:8080"
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:8080"
  dev-server:
    build: 
      context: .
      dockerfile: dev-server/Dockerfile
    ports:
      - "3002:8080"      